# Generated by Django 6.0.5 on 2026-05-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(max_length=50)),
                ('subject_name', models.CharField(max_length=100)),
                ('subject_code', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('shift', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=20)),
                ('block', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('bench_type', models.CharField(max_length=20)),
                ('rows', models.IntegerField()),
                ('cols', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=10)),
            ],
        ),
    ]
