# Generated by Django 6.0.6 on 2026-06-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='block',
            new_name='floor',
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='exam_type',
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='room',
            name='bench_type',
        ),
        migrations.RemoveField(
            model_name='room',
            name='cols',
        ),
        migrations.RemoveField(
            model_name='room',
            name='rows',
        ),
        migrations.AddField(
            model_name='examsession',
            name='time',
            field=models.TimeField(default='10:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='subject_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='subject_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(max_length=50),
        ),
    ]
