# Generated by Django 6.0.6 on 2026-06-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_block_room_floor_remove_examsession_exam_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='columns',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='rows',
            field=models.IntegerField(default=0),
        ),
    ]
