# Generated by Django 6.0.6 on 2026-06-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_room_columns_room_rows'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examsession',
            old_name='date',
            new_name='exam_date',
        ),
        migrations.RenameField(
            model_name='examsession',
            old_name='time',
            new_name='exam_time',
        ),
        migrations.AddField(
            model_name='examsession',
            name='semester',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
